name: parse_server_sdk
description: Dart package for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 1.0.27
homepage: https://github.com/AdvancedProjects/Parse-SDK-Dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.2

  # Networking
  web_socket_channel: ^1.1.0

  #Database
  sembast: ^2.4.7+6
  xxtea: ^2.0.3

  # Utils
  uuid: ^2.2.0
  meta: ^1.1.8
  path: ^1.7.0

dev_dependencies:
  # Testing
  test: ^1.15.3
  mockito: ^4.1.1
